const logger = require("../../../../Framework/FrameworkUtilities/Logger/logger");
const databaseOperations = require("../../../../Framework/FrameworkUtilities/DatabaseOperations/databaseOperations");

module.exports = {
    EMAIL_ADDRESS_GHOST_TEXTBOX: "Login/EMAIL_ADDRESS_GHOST_TEXTBOX",
    EMAIL_ADDRESS_TEXTBOX: "Login/EMAIL_ADDRESS_TEXTBOX",
    PASSWORD_GHOST_TEXTBOX: "Login/PASSWORD_GHOST_TEXTBOX",
    PASSWORD_TEXTBOX: "Login/PASSWORD_TEXTBOX",
    LOGIN_BUTTON: "Login/LOGIN_BUTTON",
    DDS_LOGIN_PAGE: "Login/DDS_LOGIN_PAGE",
    REQ_TABLE_OPTION_ICON: "OnlineStore/REQ_TABLE_OPTION_ICON",
    SEARCH_TEXTBOX: "OnlineStore/SEARCH_TEXTBOX",
    QUANTITY_TEXTBOX: "OnlineStore/QUANTITY_TEXTBOX",
    ADD_TO_CART_BUTTON : "OnlineStore/ADD_TO_CART_BUTTON",
    ADD_TO_CART_SUCCESS_MSG :"OnlineStore/ADD_TO_CART_SUCCESS_MSG",
    SUPPLIER_NAME : "OnlineStore/SUPPLIER_NAME",
    CART_ICON : "OnlineStore/CART_ICON",
    CART_ITEM_ICON : "OnlineStore/CART_ITEM_ICON",
    ONLINE_STORE_LINK : "OnlineStore/ONLINE_STORE_LINK",
    SPINNER : "OnlineStore/SPINNER",
    FAVORITE_ICON : "OnlineStore/FAVORITE_ICON",
    NO_FAV_PRODUCT_DATA_MSG : "OnlineStore/FavoritesSection/Product/NO_FAV_PRODUCT_DATA_MSG",
    VIEW_ALL_BUTTON : "OnlineStore/FavoritesSection/VIEW_ALL_BUTTON",
    MULTISELECT_MENU_ICON : "OnlineStore/FavoritesPage/MULTISELECT_MENU_ICON",
    MULTISELECT_MENU_OPTION : "OnlineStore/FavoritesPage/MULTISELECT_MENU_OPTION",
    LOAD_MORE_BUTTON : "OnlineStore/FavoritesPage/LOAD_MORE_BUTTON",
    NO_DATA_FOUND  : "OnlineStore/FavoritesPage/NO_DATA_FOUND",
    ITEM_CHECKBOX  : "OnlineStore/ITEM_CHECKBOX",
    UOM  : "OnlineStore/UOM",
    UNIT_PRICE  : "OnlineStore/UNIT_PRICE",
    USER_CURRENCY  : "OnlineStore/USER_CURRENCY",
    SUPPLIER_NAME  : "OnlineStore/SUPPLIER_NAME",
    ITEM_NAME  : "OnlineStore/ITEM_NAME",
    COMPARE_BUTTON  : "OnlineStore/COMPARE_BUTTON",
    COMPARE_GRID  : "OnlineStore/Compare/COMPARE_GRID",
    COMPARE_UNIT_PRICE  : "OnlineStore/Compare/UNIT_PRICE",
    SUPPLIER  : "OnlineStore/Compare/SUPPLIER",
    COMPARE_ITEM_NAME  : "OnlineStore/Compare/ITEM_NAME",
    FINAL_PRICE_AFTER_DISCOUNT  : "OnlineStore/Compare/FINAL_PRICE_AFTER_DISCOUNT",
    COMPARE_COLUMN  : "OnlineStore/Compare/COMPARE_COLUMN",
    BASKET_VIEW_ALL_BUTTON  : "OnlineStore/BasketSection/VIEW_ALL_BUTTON",
    BASKET_NAME  : "OnlineStore/BasketPage/BASKET_NAME",
    BASKET_SORT_ICON  : "OnlineStore/BasketPage/BASKET_SORT_ICON",
    BASKET_SORT_ORDER_LABEL  : "OnlineStore/BasketPage/BASKET_SORT_ORDER_LABEL",

    CREATE_REQUEST_BUTTON : "OnlineStore/CREATE_REQUEST_BUTTON",

};

