var Product = "TMS";
export let CreateRoleObj= {
  
  //SearchRes: "//td/label[text()='ZCS']",

  //RoleManagementTab: "//a[text()='Role Management']",
  RoleManagementTab: "CREATEROLE/RoleManagementTab",
  //AddNewRoleBtn: "//a[@title='Add New Role']",
  AddNewRoleBtn: "CREATEROLE/AddNewRoleBtn",
  //RoleTitleTxtBox: "//input[@name='txtRoleTitle']",
  RoleTitleTxtBox: "CREATEROLE/RoleTitleTxtBox",
  //RoleDesc: "//textarea[@name='RoleDescription']",
  RoleDesc: "CREATEROLE/RoleDesc",
  //ProductSelection: "//select[@class='frmEle']/option[@value='TMS']",
  //ProductSelection: '//select[@class="frmEle"]/option[@value="'+Product+'"]',
  ProductSelection: "CREATEROLE/ProductSelection",
  SaveBtn: "CREATEROLE/SaveBtn",
  selectCheck: "CREATEROLE/selectCheck",
  selectmainactcheck: "CREATEROLE/selectmainactcheck",
  selectCAsubactheck: "CREATEROLE/selectCAsubactheck",
  selectPreferencessubactheck: "CREATEROLE/selectPreferencessubactheck",
  selectAudittrailsubactheck: "CREATEROLE/selectAudittrailsubactheck",
  selectReportssubactheck: "CREATEROLE/selectReportssubactheck",
  selectUsermanagementsubactheck: "CREATEROLE/selectUsermanagementsubactheck",
  selectWorkflowsubactheck: "CREATEROLE/selectWorkflowsubactheck",
  selectMasterdatasubactheck: "CREATEROLE/selectMasterdatasubactheck",
  selectRolemanagementsubactheck: "CREATEROLE/selectRolemanagementsubactheck",
  RoleActassignEditBtn:"CREATEROLE/RoleActassignEditBtn",
  selectLAsubactheck: "CREATEROLE/selectLAsubactheck",
  RolebasicBackBtn:"CREATEROLE/RolebasicBackBtn",
  AcvtivityassignedtoroleCA:"CREATEROLE/AcvtivityassignedtoroleCA",
  RoleMainCancelBtn:"CREATEROLE/RoleMainCancelBtn",
  SaveBtn2: "CREATEROLE/SaveBtn2",
  DoneBtn: "CREATEROLE/DoneBtn",
  SearchRole: "CREATEROLE/SearchRole",
  // SearchRole: "//input[@name='eventSearchText']",
  // GoBtn: "//input[@value='Go']",
  GoBtn: "CREATEROLE/GoBtn",
  // AssignRole: "CREATEROLE/Confirmation",
  AssignRole: "CREATEROLE/AssignRole",
  // AddUser: "//tbody/tr[1]/td[1]/*",
  AddUser: "CREATEROLE/AddUser",
  // SaveBtn3: "//input[@value='Save and Close']",
  SaveBtn3: "CREATEROLE/SaveBtn3",
  // Deactivate: "//label[@title='Active Role']",
  Deactivate: "CREATEROLE/Deactivate",
  // Activate: "//label[@title='Inactive Role']",
  Activate: "CREATEROLE/Activate",
  // Confirmation: "//button[@role='button']/span[text()='Ok']",
  Confirmation: "CREATEROLE/Confirmation",
  // EditRole: "//label[@title= 'Edit Role Information']",
  EditRole: "CREATEROLE/EditRole",
  // EditRoleInfo: "//span[text()='Role Definition']/following-sibling::label[text()='Edit']",
  EditRoleInfo: "CREATEROLE/EditRoleInfo",
  // EditRoleAct: "//span[text()='Activities Allocated']/following-sibling::label[text()='Edit']",
  EditRoleAct: "CREATEROLE/EditRoleAct",
  // UpdateSave: "//input[@name='Update and Continue']",
  UpdateSave: "CREATEROLE/UpdateSave",


  // RLType: "//select[@id='cmbRoleType']",
  RLType: "CREATEROLE/RLType",
  // RLValue: "/option[@value='System Role']",
  RLValue: "CREATEROLE/RLValue",
  // Prod: "//select[@id='cmbAssignProduct']",
  Prod: "CREATEROLE/Prod",
  // SelectProd: "//select[@class='dropdown2 frmEle']/option[@value='TMS'][text()='TMS']",
  SelectProd: "CREATEROLE/SelectProd",
  // SP: "//select[@id='cmbAssignProduct']/option[@value='SPM']",
  SP: "CREATEROLE/SP",
  // RLDesc: "//textarea[@id='RoleDescription']",
  RLDesc: "CREATEROLE/RLDesc",
  // SaveContinue: "//input[@title='Save and Continue']",
  SaveContinue: "CREATEROLE/SaveContinue",
  // ZA_UpdateSave: "//input[@title='Update and Continue']",
  ZA_UpdateSave: "CREATEROLE/UpdateSave",

  // Company: "//a[@id='COMPANY']",
  Company: "CREATEROLE/Company",
  // CompSearch: "//input[@id='eventSearchText']",
  CompSearch: "CREATEROLE/CompSearch",
  // UserListingIcon: "//label[@title='Manage Users and Roles for this Company']",
  UserListingIcon: "CREATEROLE/UserListingIcon",
  // ZA_Deactivate: "//label[@title='Active Role']",
  ZA_Deactivate: "CREATEROLE/ZA_Deactivate",


  //RoleManagementTab: "//a[text()='Role Management']",
  Role_type: "//select[@id='searchColumn']",
  ViewRole: "//label[@title='View Role Information']",
  //SearchRole: "//input[@name='eventSearchText']",
  //GoBtn: "//input[@value='Go']",
}