module.exports = {
    EMAIL_ADDRESS_TEXTBOX: "Login/ELEMENT_ADDRESS_TEXTBOX",
    PASSWORD_TEXTBOX: "Login/PASSWORD_TEXTBOX",
    LOGIN_BUTTON: "Login/LOGIN_BUTTON",
    MENU_PAGE: "Login/MENU_PAGE",
    MENU_iREQUEST:"Login/MENU_iREQUEST"

}