module.exports = {
    CREATE_REQ_BTN:'CreateReq/CREATE_REQ_BTN',
    SEARCH_RD_BUTTON:'CreateReq/SEARCH_RD_BUTTON',
    CREATE_REQ_POPUP:'CreateReq/CREATE_POPUP',
    REQ_NAME_INPUT:'CreateReq/REQ_NAME_INPUT',
    URGNT_YES_BUTTON:'CreateReq/URGNT_YES_BTN',
    REASON_URGENCY_TEXTBOX:'CreateReq/REASON_URGNCY_TEXTBOX',
    ATTACHMENT_BUTTON:'CreateReq/ATTACHMENT_BUTTON',
    SUBMIT_BUTTON:'CreateReq/SUBMIT_BUTTON',
    CANCEL_BUTTON:'CreateReq/CANCEL_BUTTON',
    RD_SELECTION_OPTION:'CreateReq/RD_SELECTION_OPTION',
    RD_MOUSEOVER_ID:'CreateReq/RD_MOUSEOVER_ID',
    SUBMIT_DONE_BUTTON:'CreateReq/SUBMIT_DONE_BTN',
    SAVE_AS_DRAFT_BTN:'CreateReq/SAVEASDRAFT_BTN',
    ISOURCE_ITEM_NAME:'iSource/ITEM_NAME',
    ISOURCE_PRICE_TYPE_OPTION:'iSource/PRICE_TYPE_OPTION',
    ISOURCE_UNIT_TYPE:'iSource/UNIT_TYPE',
    ISOURCE_ITEM_NUMBER:'iSource/ITEM_NUMBER',
    ISOURCE_UNIT_OF_MEASURES:'iSource/UNIT_OF_MEASURES',
    ISOURCE_QUANTITY:'iSource/QUANTITY',
    ISOURCE_EVENT_CURRENCY_SELECTION:'iSource/EVENT_CURRENCY_SELECTION',
    ISOURCE_EVENT_CURRENCY:'iSource/EVENT_CURRENCY'


}