module.exports={
BLANKET_PO_BUTTON : 'Bpo/BLANKET_PO_BUTTON',
ORDER_VALUE: 'Bpo/AgreementDetails/ORDER_VALUE',
AUTO_UPDATE_CHECKBOX: 'Bpo/AgreementDetails/AUTO_UPDATE_CHECKBOX',
DEFINE_BUYING_SCOPE: 'Bpo/AgreementDetails/DEFINE_BUYING_SCOPE',
BUSINESS_UNIT_DROPDOWN: 'Bpo/AgreementDetails/BUSINESS_UNIT_DROPDOWN',
LOCATION_DROPDOWN: 'Bpo/AgreementDetails/LOCATION_DROPDOWN',
COST_CENTER_DROPDOWN: 'Bpo/AgreementDetails/COST_CENTER_DROPDOWN',
OK_BUTTON: 'Bpo/AgreementDetails/OK_BUTTON',
PREVENT_ITEMS_OF_OTHER_CATEGORY_CHECKBOX: 'Bpo/Settings/PREVENT_ITEMS_OF_OTHER_CATEGORY_CHECKBOX',
PREVENT_CHANGE_ON_RELEASE_ORDER_CHECKBOX: 'Bpo/Settings/PREVENT_CHANGE_ON_RELEASE_ORDER_CHECKBOX',
PREVENT_FROM_EXCEEDING_ORDER_VALUE_CHECKBOX: 'Bpo/Settings/PREVENT_FROM_EXCEEDING_ORDER_VALUE_CHECKBOX',
BUSINESS_UNIT_LOCATION_SELECTION: 'Bpo/AgreementDetails/BUSINESS_UNIT_LOCATION_SELECTION',
FROM_DATE: 'Bpo/Validity/FROM_DATE',
TO_DATE: 'Bpo/Validity/TO_DATE',
ACCEPT_INVOICES_UNTIL: 'Bpo/Validity/ACCEPT_INVOICES_UNTIL',

}