export let CompanyObj = {


    //CREATE_NEW_COMPANY :".//*[@title='Create New Company']",
    CREATE_NEW_COMPANY :"COMPANY/CREATE_NEW_COMPANY",
    //COMPANY_NAME :".//*[@id='companyName']",
    COMPANY_NAME :"COMPANY/COMPANY_NAME",
    //IS_SAAS_PROVIDER :".//*[@id='isSaasCompany']",
    IS_SAAS_PROVIDER :"COMPANY/IS_SAAS_PROVIDER",
    //IS_DELEGATED_COMPANY :".//*[@id='isDelegatedCompany']",
    IS_DELEGATED_COMPANY :"COMPANY/IS_DELEGATED_COMPANY",
    //IS_ZAUTH_COMPANY :".//*[@id='iszAuthCompany']",
    IS_ZAUTH_COMPANY :"COMPANY/IS_ZAUTH_COMPANY",
    //COMPANY_ALIAS: ".//*[@id='idpAlias']",
    COMPANY_ALIAS: "COMPANY/COMPANY_ALIAS",
    COMPANY_PARENT: "COMPANY/COMPANY_PARENT",
    //COMPANY_PARENT_Locator: "COMPANY/COMPANY_PARENT_Locator",
    COMPANY_PARENT_Locator: ".//*[@id='parentCompanyName']",
    //COMPANY_PARENT_Selector:"//li[@title='ZCS integration-test']", //a[contains(text(),'Download Dynamic Excel Template')]
    COMPANY_PARENT_Selector:".//*[@id='companyUserList']",
    //BRIDGE_URL :".//*[@id='bridgeUrl']",
    BRIDGE_URL :"COMPANY/BRIDGE_URL",
    //DOMAIN_URL :".//*[@id='domainUrl']",
    DOMAIN_URL :"COMPANY/DOMAIN_URL",
    //LOGIN_THROUGH_UNIQUE_ID :".//*[@id='isUniqueIdAuthentication']",
    LOGIN_THROUGH_UNIQUE_ID :"COMPANY/LOGIN_THROUGH_UNIQUE_ID",
    IS_CHILD_COMPANY : "COMPANY/IS_CHILD_COMPANY",
    //IS_SCOPE_ENABLED :".//*[@id='isScopeEnabled']",
    IS_SCOPE_ENABLED :"COMPANY/IS_SCOPE_ENABLED",
    //COMPANY_LOCATION :".//*[@id='locationName']",
    COMPANY_LOCATION :"COMPANY/COMPANY_LOCATION",
    //COMPANY_ADDRESS1 :".//*[@id='address1']",
    COMPANY_ADDRESS1 :"COMPANY/COMPANY_ADDRESS1",
    //COMPANY_ADDRESS2 :".//*[@id='address2']",
    COMPANY_ADDRESS2 :"COMPANY/COMPANY_ADDRESS2",
    //COMPANY_CITY :".//*[@id='city']",
    COMPANY_CITY :"COMPANY/COMPANY_CITY",
    //COMPANY_STATE :".//*[@id='state']",
    COMPANY_STATE :"COMPANY/COMPANY_STATE",
    //COMPANY_ZIPCODE :".//*[@id='zipCode']",
    COMPANY_ZIPCODE :"COMPANY/COMPANY_ZIPCODE",
    //COMPANY_COUNTRY :".//*[@id='country']",
    COMPANY_COUNTRY :"COMPANY/COMPANY_COUNTRY",
    //COMPANY_CONTINUE_NEXT_STEP :".//*[@title='Continue']",
    COMPANY_CONTINUE_NEXT_STEP :"COMPANY/COMPANY_CONTINUE_NEXT_STEP",
    //COMPANY_ENABLE_RAINBOW :".//*[@id='rainbowCheck']",
    COMPANY_ENABLE_RAINBOW :"COMPANY/COMPANY_ENABLE_RAINBOW",
    //COMPANY_ENABLE_CRMS :"crmsCheck",
    COMPANY_ENABLE_CRMS :"COMPANY/COMPANY_ENABLE_CRMS",
    //COMPANY_ENABLE_COMMONWORKFLOW :".//*[@id='commonWorkflowCheck']",
    COMPANY_ENABLE_COMMONWORKFLOW :"COMPANY/COMPANY_ENABLE_COMMONWORKFLOW",
    //COMPANY_ENABLE_ONEVIEW :".//*[@id='oneViewCheck']",
    COMPANY_ENABLE_ONEVIEW :"COMPANY/COMPANY_ENABLE_ONEVIEW",
    //COMPANY_ENABLE_DEWDROP :".//*[@id='dewDropCheck']",
    COMPANY_ENABLE_DEWDROP :"COMPANY/COMPANY_ENABLE_DEWDROP",
    //COMPANY_ENABLE_BUP :".//*[@id='bupCheck']",
    COMPANY_ENABLE_BUP :"COMPANY/COMPANY_ENABLE_BUP",

/*
    COMPANY_ADMIN_FIRST_NAME :".//*[@id='firstName']",
    COMPANY_ADMIN_LAST_NAME :".//*[@id='lastName']",
    COMPANY_ADMIN_DISPLAY_NAME :".//*[@id='displayName']",
    COMPANY_ADMIN_EMAIL :".//*[@id='emailId']",
    COMPANY_ADMIN_UNIQUE_ID_TYPE :".//*[@id='uniqueKeyType']",
    COMPANY_ADMIN_UNIQUE_ID_VALUE :".//*[@id='uniqueIdValue']",
    COMPANY_ADMIN_ADD_UNIQUE_ID :".//*[@id='addUniqueValue']",
    COMPANY_BACK_TO_PREVIOUS_PAGE :".//*[@name='back']",
    COMPANY_CANCEL :".//*[@name='cancel']",
    COMPANY_TIMEZONE :".//*[@id='timeZone']/following-sibling::input",
    COMPANY_NUMBER_FORMAT :".//*[@id='numberFormat']",
    COMPANY_DATE_FORMAT :".//*[@id='defaultDateFormat']",
    COMPANY_TIME_FORMAT :".//*[@id='timeFormat']",
    COMPANY_CURRENCY :".//*[@id='defaultCurrency']",
    COMPANY_LOCALE :".//*[@id='defaultLocale']",
    COMPANY_SMTP_SERVER_ID :".//*[@id='SMTPServerId']",
    COMPANY_PORT_NUMBER :".//*[@id='portnumber']",
    COMPANY_DECIMAL_PRECISION :".//*[@id='decimalPrecision']",
    COMPANY_FISCAL_YEAR :".//*[@id='fiscalyearstart']",
    COMPANY_DEFINE_COMPANY :".//*[@id='mainButton']",
    COMPANY_SUCCESS_MESSAGE :".//*[@class='tblcellmsg']",
    COMPANY_SUCCESS_POPUP_OK_BUTTON :"html/body/div[4]/div[3]/div/button",
*/
    COMPANY_ADMIN_FIRST_NAME :'COMPANY/COMPANY_ADMIN_FIRST_NAME',
COMPANY_ADMIN_LAST_NAME :'COMPANY/COMPANY_ADMIN_LAST_NAME',
COMPANY_ADMIN_DISPLAY_NAME :'COMPANY/COMPANY_ADMIN_DISPLAY_NAME',
COMPANY_ADMIN_EMAIL :'COMPANY/COMPANY_ADMIN_EMAIL',
COMPANY_ADMIN_UNIQUE_ID_TYPE :'COMPANY/COMPANY_ADMIN_UNIQUE_ID_TYPE',
COMPANY_ADMIN_UNIQUE_ID_VALUE :'COMPANY/COMPANY_ADMIN_UNIQUE_ID_VALUE',
COMPANY_ADMIN_ADD_UNIQUE_ID :'COMPANY/COMPANY_ADMIN_ADD_UNIQUE_ID',
COMPANY_BACK_TO_PREVIOUS_PAGE :'COMPANY/COMPANY_BACK_TO_PREVIOUS_PAGE',
COMPANY_CANCEL :'COMPANY/COMPANY_CANCEL',
COMPANY_TIMEZONE :'COMPANY/COMPANY_TIMEZONE',
COMPANY_NUMBER_FORMAT :'COMPANY/COMPANY_NUMBER_FORMAT',
COMPANY_DATE_FORMAT :'COMPANY/COMPANY_DATE_FORMAT',
COMPANY_TIME_FORMAT :'COMPANY/COMPANY_TIME_FORMAT',
COMPANY_CURRENCY :'COMPANY/COMPANY_CURRENCY',
COMPANY_LOCALE :'COMPANY/COMPANY_LOCALE',
COMPANY_SMTP_SERVER_ID :'COMPANY/COMPANY_SMTP_SERVER_ID',
COMPANY_PORT_NUMBER :'COMPANY/COMPANY_PORT_NUMBER',
COMPANY_DECIMAL_PRECISION :'COMPANY/COMPANY_DECIMAL_PRECISION',
COMPANY_FISCAL_YEAR :'COMPANY/COMPANY_FISCAL_YEAR',
COMPANY_DEFINE_COMPANY :'COMPANY/COMPANY_DEFINE_COMPANY',
COMPANY_SUCCESS_MESSAGE :'COMPANY/COMPANY_SUCCESS_MESSAGE',
COMPANY_SUCCESS_POPUP_OK_BUTTON :'COMPANY/COMPANY_SUCCESS_POPUP_OK_BUTTON',





    /* COMPANY_TMS_URL :".//*[@name='TMS_Url']",
    COMPANY_TMS_ACTIVATE :".//*[@name='TMS_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_TMS_DEACTIVATE :".//*[@name='TMS_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_SPM_URL :".//*[@name='SPM_Url']",
    COMPANY_SPM_ACTIVATE :".//*[@name='SPM_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_SPM_DEACTIVATE :".//*[@name='SPM_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_SIM_URL :".//*[@name='SIM_Url']",
    COMPANY_SIM_ACTIVATE :".//*[@name='SIM_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_SIM_DEACTIVATE :".//*[@name='SIM_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_CENTRALRMS_URL :".//*[@name='CentralRMS_Url']",
    COMPANY_CENTRALRMS_ACTIVATE :".//*[@name='CentralRMS_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_CENTRALRMS_DEACTIVATE :".//*[@name='CentralRMS_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_FIELD_LIBRARY_URL :".//*[@name='Field Library_Url']",
    COMPANY_FIELD_LIBRARY_ACTIVATE :".//*[@name='Field Library_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_FIELD_LIBRARY_DEACTIVATE :".//*[@name='Field Library_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_IMPORT_STUDIO_URL :".//*[@name='Import Studio_Url']",
    COMPANY_IMPORT_STUDIO_ACTIVATE :".//*[@name='Import Studio_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_IMPORT_STUDIO_DEACTIVATE :".//*[@name='Import Studio_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_MAS_URL :".//*[@name='MAS_Url']",
    COMPANY_MAS_ACTIVATE :".//*[@name='MAS_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_MAS_DEACTIVATE :".//*[@name='MAS_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_ECATALOG_URL :".//*[@name='eCatalog_Url']",
    COMPANY_ECATALOG_ACTIVATE :".//*[@name='eCatalog_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_ECATALOG_DEACTIVATE :".//*[@name='eCatalog_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_EINVOICE_URL :".//*[@name='eInvoice_Url']",
    COMPANY_EINVOICE_ACTIVATE :".//*[@name='eInvoice_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_EINVOICE_DEACTIVATE :".//*[@name='eInvoice_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_EPROC_URL :".//*[@name='eProc_Url']",
    COMPANY_EPROC_ACTIVATE :".//*[@name='eProc_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_EPROC_DEACTIVATE :".//*[@name='eProc_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_IANALYZE_URL :".//*[@name='iAnalyze_Url']",
    COMPANY_IANALYZE_ACTIVATE :".//*[@name='iAnalyze_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_IANALYZE_DEACTIVATE :".//*[@name='iAnalyze_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_ICONSOLE_URL :".//*[@name='iConsole_Url']",
    COMPANY_ICONSOLE_ACTIVATE :".//*[@name='iConsole_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_ICONSOLE_DEACTIVATE :".//*[@name='iConsole_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_ICONTRACT_URL :".//*[@name='iContract_Url']",
    COMPANY_ICONTRACT_ACTIVATE :".//*[@name='iContract_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_ICONTRACT_DEACTIVATE :".//*[@name='iContract_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_ICOST_URL :".//*[@name='iCost_Url']",
    COMPANY_ICOST_ACTIVATE :".//*[@name='iCost_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_ICOST_DEACTIVATE :".//*[@name='iCost_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_IMANAGE_URL :".//*[@name='iManage_Url']",
    COMPANY_IMANAGE_ACTIVATE :".//*[@name='iManage_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_IMANAGE_DEACTIVATE :".//*[@name='iManage_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_IREQUEST_URL :".//*[@name='iRequest_Url']",
    COMPANY_IREQUEST_ACTIVATE :".//*[@name='iRequest_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_IREQUEST_DEACTIVATE :".//*[@name='iRequest_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_ISAVE_URL :".//*[@name='iSave_Url']",
    COMPANY_ISAVE_ACTIVATE :".//*[@name='iSave_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_ISAVE_DEACTIVATE :".//*[@name='iSave_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_ISOURCE_URL :".//*[@name='iSource_Url']",
    COMPANY_ISOURCE_ACTIVATE :".//*[@name='iSource_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_ISOURCE_DEACTIVATE :".//*[@name='iSource_Url']/../../following-sibling::td/a[@class='activateIcon']",
    COMPANY_LMT_URL:".//*[@name='Language Management Tool_Url']",
    COMPANY_LMT_ACTIVATE :".//*[@name='Language Management Tool_Url']/../../following-sibling::td/a[@class='deactivateIcon']",
    COMPANY_SHT_URL:".//*[@name='SelfHelpComponent_Url']",
    COMPANY_SHT_ACTIVATE :".//*[@name='SelfHelpComponent_Url']/../../following-sibling::td/a[@class='deactivateIcon']", */


COMPANY_TMS_URL :'COMPANY/COMPANY_TMS_URL',
COMPANY_TMS_ACTIVATE :'COMPANY/COMPANY_TMS_ACTIVATE',
COMPANY_TMS_DEACTIVATE :'COMPANY/COMPANY_TMS_DEACTIVATE',
COMPANY_SPM_URL :'COMPANY/COMPANY_SPM_URL',
COMPANY_SPM_ACTIVATE :'COMPANY/COMPANY_SPM_ACTIVATE',
COMPANY_SPM_DEACTIVATE :'COMPANY/COMPANY_SPM_DEACTIVATE',
COMPANY_SIM_URL :'COMPANY/COMPANY_SIM_URL',
COMPANY_SIM_ACTIVATE :'COMPANY/COMPANY_SIM_ACTIVATE',
COMPANY_SIM_DEACTIVATE :'COMPANY/COMPANY_SIM_DEACTIVATE',
COMPANY_CENTRALRMS_URL :'COMPANY/COMPANY_CENTRALRMS_URL',
COMPANY_CENTRALRMS_ACTIVATE :'COMPANY/COMPANY_CENTRALRMS_ACTIVATE',
COMPANY_CENTRALRMS_DEACTIVATE :'COMPANY/COMPANY_CENTRALRMS_DEACTIVATE',
COMPANY_FIELD_LIBRARY_URL :'COMPANY/COMPANY_FIELD_LIBRARY_URL',
COMPANY_FIELD_LIBRARY_ACTIVATE :'COMPANY/COMPANY_FIELD_LIBRARY_ACTIVATE',
COMPANY_FIELD_LIBRARY_DEACTIVATE :'COMPANY/COMPANY_FIELD_LIBRARY_DEACTIVATE',
COMPANY_IMPORT_STUDIO_URL :'COMPANY/COMPANY_IMPORT_STUDIO_URL',
COMPANY_IMPORT_STUDIO_ACTIVATE :'COMPANY/COMPANY_IMPORT_STUDIO_ACTIVATE',
COMPANY_IMPORT_STUDIO_DEACTIVATE :'COMPANY/COMPANY_IMPORT_STUDIO_DEACTIVATE',
COMPANY_MAS_URL :'COMPANY/COMPANY_MAS_URL',
COMPANY_MAS_ACTIVATE :'COMPANY/COMPANY_MAS_ACTIVATE',
COMPANY_MAS_DEACTIVATE :'COMPANY/COMPANY_MAS_DEACTIVATE',
COMPANY_ECATALOG_URL :'COMPANY/COMPANY_ECATALOG_URL',
COMPANY_ECATALOG_ACTIVATE :'COMPANY/COMPANY_ECATALOG_ACTIVATE',
COMPANY_ECATALOG_DEACTIVATE :'COMPANY/COMPANY_ECATALOG_DEACTIVATE',
COMPANY_EINVOICE_URL :'COMPANY/COMPANY_EINVOICE_URL',
COMPANY_EINVOICE_ACTIVATE :'COMPANY/COMPANY_EINVOICE_ACTIVATE',
COMPANY_EINVOICE_DEACTIVATE :'COMPANY/COMPANY_EINVOICE_DEACTIVATE',
COMPANY_EPROC_URL :'COMPANY/COMPANY_EPROC_URL',
COMPANY_EPROC_ACTIVATE :'COMPANY/COMPANY_EPROC_ACTIVATE',
COMPANY_EPROC_DEACTIVATE :'COMPANY/COMPANY_EPROC_DEACTIVATE',
COMPANY_IANALYZE_URL :'COMPANY/COMPANY_IANALYZE_URL',
COMPANY_IANALYZE_ACTIVATE :'COMPANY/COMPANY_IANALYZE_ACTIVATE',
COMPANY_IANALYZE_DEACTIVATE :'COMPANY/COMPANY_IANALYZE_DEACTIVATE',
COMPANY_ICONSOLE_URL :'COMPANY/COMPANY_ICONSOLE_URL',
COMPANY_ICONSOLE_ACTIVATE :'COMPANY/COMPANY_ICONSOLE_ACTIVATE',
COMPANY_ICONSOLE_DEACTIVATE :'COMPANY/COMPANY_ICONSOLE_DEACTIVATE',
COMPANY_ICONTRACT_URL :'COMPANY/COMPANY_ICONTRACT_URL',
COMPANY_ICONTRACT_ACTIVATE :'COMPANY/COMPANY_ICONTRACT_ACTIVATE',
COMPANY_ICONTRACT_DEACTIVATE :'COMPANY/COMPANY_ICONTRACT_DEACTIVATE',
COMPANY_ICOST_URL :'COMPANY/COMPANY_ICOST_URL',
COMPANY_ICOST_ACTIVATE :'COMPANY/COMPANY_ICOST_ACTIVATE',
COMPANY_ICOST_DEACTIVATE :'COMPANY/COMPANY_ICOST_DEACTIVATE',
COMPANY_IMANAGE_URL :'COMPANY/COMPANY_IMANAGE_URL',
COMPANY_IMANAGE_ACTIVATE :'COMPANY/COMPANY_IMANAGE_ACTIVATE',
COMPANY_IMANAGE_DEACTIVATE :'COMPANY/COMPANY_IMANAGE_DEACTIVATE',
COMPANY_IREQUEST_URL :'COMPANY/COMPANY_IREQUEST_URL',
COMPANY_IREQUEST_ACTIVATE :'COMPANY/COMPANY_IREQUEST_ACTIVATE',
COMPANY_IREQUEST_DEACTIVATE :'COMPANY/COMPANY_IREQUEST_DEACTIVATE',
COMPANY_ISAVE_URL :'COMPANY/COMPANY_ISAVE_URL',
COMPANY_ISAVE_ACTIVATE :'COMPANY/COMPANY_ISAVE_ACTIVATE',
COMPANY_ISAVE_DEACTIVATE :'COMPANY/COMPANY_ISAVE_DEACTIVATE',
COMPANY_ISOURCE_URL :'COMPANY/COMPANY_ISOURCE_URL',
COMPANY_ISOURCE_ACTIVATE :'COMPANY/COMPANY_ISOURCE_ACTIVATE',
COMPANY_ISOURCE_DEACTIVATE :'COMPANY/COMPANY_ISOURCE_DEACTIVATE',
COMPANY_LMT_URL:'COMPANY/COMPANY_LMT_URL',
COMPANY_LMT_ACTIVATE :'COMPANY/COMPANY_LMT_ACTIVATE',
COMPANY_SHT_URL:'COMPANY/COMPANY_SHT_URL',
COMPANY_SHT_ACTIVATE :'COMPANY/COMPANY_SHT_ACTIVATE',

    
    COMPANY_SHT_URL_DATA: "https://dewdrops-partner.zycus.com/sht",
    COMPANY_LMT_URL_DATA: "https://dewdrops-partner.zycus.com/lmt",
    COMPANY_TMS_URL_DATA: "https://tenants-partner.zycus.com/tms",
    COMPANY_SIM_URL_DATA: "https://sim-partner.zycus.com/sim/",
    COMPANY_FIELD_LIBRARY_URL_DATA: "https://fieldlibrary-partner.zycus.com/fieldlibrary/",
    COMPANY_EPROC_URL_DATA: "https://eproc-partner.zycus.com/eproc",
    COMPANY_IREQUEST_URL_DATA: "https://irequest-partner.zycus.com/irequest",
    





    COMPANY_TMS_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'TMS')]/following-sibling::td/a",
    COMPANY_SPM_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'SPM')]/following-sibling::td/a",
    COMPANY_SIM_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'SIM')]/following-sibling::td/a",
    COMPANY_EPROC_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'eProc')]/following-sibling::td/a",
    COMPANY_EINVOICE_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'eInvoice')]/following-sibling::td/a",
    COMPANY_IANALYZE_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'iAnalyze')]/following-sibling::td/a",
    COMPANY_ICONTRACT_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'iContract')]/following-sibling::td/a",
    COMPANY_ISOURCE_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'iSource')]/following-sibling::td/a",
    COMPANY_ISAVE_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'iSave')]/following-sibling::td/a",
    COMPANY_ICOST_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'iCost')]/following-sibling::td/a",
    COMPANY_IMANAGE_REGISTRY :".//*[@id='wrapper']//td[contains(text(),'iManage')]/following-sibling::td/a",
    COMPANY_REGISTRY_KEY :".//*[@id='key']",
    COMPANY_REGISTRY_VALUE :".//*[@id='value']",
    COMPANY_ADD_REGISTRY :".//*[@name='Save']",
    COMPANY_REGISTRY_OVERRIDE_MESSAGE :".//*[@id='ui-id-1']/table/tbody/tr/td[2]",
    COMPANY_REGISTRY_OVERRIDE_MESSAGE_OK :"html/body/div[4]/div[3]/div/button[1]",
    COMPANY_BACK_TO_SUMMARY_PAGE :".//*[@class='fR backArrow icon scLnk']",
    COMPANY_UPDATE_COMPANY :".//*[@id='mainButton']",
    COMPANY_UPDATE_SUCCESS_MESSAGE :".//*[@id='ui-id-1']/table/tbody/tr/td[2]",
    COMPANY_UPDATE_SUCCESS_MESSAGE_OK :"html/body/div[4]/div[3]/div/button",
    COMPANY_EDIT_PRODUCT :".//*/span[text()='Component Selection & Product Allocation']/following-sibling::label[@class='icon edit']",
    
    COMPANY_NAME_DATA:"testC126",
    COMPANY_BRIDGE_URL_DATA:"https://testC125.zycus.com/fedlet/handle",
    COMPANY_DOMAIN_URL_DATA:"testC125.zycus.com",
    COMPANY_LOCATION_DATA:"Location",
    COMPANY_ADDRESS1_DATA:"Address1",
    COMPANY_ADDRESS2_DATA:"Address2",
    COMPANY_CITY_DATA:"City",
    COMPANY_STATE_DATA:"State",
    COMPANY_ZIPCODE_DATA:"123456",
    COMPANY_COUNTRY_DATA:"India",
    COMPANY_TMS_PRODUCT_URL_DATA:"https://smttenants.zycus.net/tms",
    COMPANY_CA_FIRST_NAME_DATA:"CAFN_testC126",
    COMPANY_CA_LAST_NAME_DATA:"CALN_testC126",
    COMPANY_CA_DISPLAY_NAME_DATA:"CADN_testC126",
    COMPANY_CA_EMAIL_ADDRESS_DATA:"CA@testC126.com",
    COMPANY_CA_UNIQUE_ID_TYPE_DATA:"ERP ID",
    COMPANY_CA_UNIQUE_ID_VALUE_DATA:"CA_testC125",
    COMPANY_TIMEZONE_DATA:"ACT - (GMT+09:30)",
    COMPANY_NUMBER_FORMAT_DATA:"#,###,###.##",
    COMPANY_DATE_FORMAT_DATA:"MM/dd/yyyy",
    COMPANY_TIME_FORMAT_DATA:"12 Hours",
    COMPANY_CURRENCY_DATA:"INR - Indian Rupee",
    COMPANY_LOCALE_DATA:"English (US)",
    COMPANY_SMTP_SERVER_ID_DATA:"webmail.zycus.net",
    COMPANY_PORT_DATA:"25",
    COMPANY_DECIMAL_PRECISION_DATA:"5",
    COMPANY_FISCAL_YEAR_DATA:"27-04",
    
    /*
    COMPANY_USER_LISTING :".//*[@id='company-grid']//td[contains(text(),'001')]/following-sibling::td/label[@title='Manage Users and Roles for this Company']",
    EDIT_COMPANY :".//*[@id='company-grid']//td[contains(text(),'001')]/following-sibling::td/label[@title='Edit Company Information']",
    DEACTIVATE_COMPANY :".//*[@id='company-grid']//td[contains(text(),'001')]/following-sibling::td/label[@title='Active Company']",
    REACTIVATE_COMPANY :".//*[@id='company-grid']//td[contains(text(),'001')]/following-sibling::td/label[@title='Inactive Company']",
    COMPANY_LISTING_SEARCH_BY :".//*[@id='searchColumn']",
    COMPANY_LISTING_SEARCH_BY_VALUE :".//*[@id='eventSearchText']",
    COMPANY_LISTING_SEARCH_COMPANY_BUTTON :".//*[@name='SearchButton']",
    COMPANY_LISTING_COMPANIES_TAB :".//*[@id='COMPANY']",
    COMPANY_LISTING_PRODUCTS_TAB :".//*[@id='PRODUCT']",
    COMPANY_LISTING_ADMINISTRATOR_TAB :".//*[@id='ADMINISTRATOR']",
    COMPANY_LISTING_LIVE_SESSIONS_TAB :".//*[@id='LIVE_SESSION']",
    COMPANY_LISTING_APPLY_SETTINGS_TAB :".//*[@id='APPLY_SETTINGS']",
    COMPANY_LISTING_IMPERSONATE_USER_REQUESTS_TAB :".//*[@id='IMPERSONATE_USER_REQUESTS']",
    COMPANY_LISTING_ROLE_MANAGEMENT_TAB :".//*[@id='ROLE_MANAGEMENT']",
    COMPANY_LISTING_ROLE_REPORTS_TAB :".//*[@id='REPORTS']",
    COMPANY_LISTING_SEARCH_PAGE_NO :".//*[@class='textInput']",
    COMPANY_LISTING_NEXT_PAGE :".//*[@class='next']",
    COMPANY_LISTING_LAST_PAGE :".//*[@class='last']",
    COMPANY_LISTING_FIRST_PAGE :".//*[@class='first']",
    COMPANY_LISTING_PREVIOUS_PAGE :".//*[@class='previous']",

    */
   COMPANY_USER_LISTING :'COMPANY/COMPANY_USER_LISTING',
EDIT_COMPANY :'COMPANY/EDIT_COMPANY',
DEACTIVATE_COMPANY :'COMPANY/DEACTIVATE_COMPANY',
REACTIVATE_COMPANY :'COMPANY/REACTIVATE_COMPANY',
COMPANY_LISTING_SEARCH_BY :'COMPANY/COMPANY_LISTING_SEARCH_BY',
COMPANY_LISTING_SEARCH_BY_VALUE :'COMPANY/COMPANY_LISTING_SEARCH_BY_VALUE',
COMPANY_LISTING_SEARCH_COMPANY_BUTTON :'COMPANY/COMPANY_LISTING_SEARCH_COMPANY_BUTTON',
COMPANY_LISTING_COMPANIES_TAB :'COMPANY/COMPANY_LISTING_COMPANIES_TAB',
COMPANY_LISTING_PRODUCTS_TAB :'COMPANY/COMPANY_LISTING_PRODUCTS_TAB',
COMPANY_LISTING_ADMINISTRATOR_TAB :'COMPANY/COMPANY_LISTING_ADMINISTRATOR_TAB',
COMPANY_LISTING_LIVE_SESSIONS_TAB :'COMPANY/COMPANY_LISTING_LIVE_SESSIONS_TAB',
COMPANY_LISTING_APPLY_SETTINGS_TAB :'COMPANY/COMPANY_LISTING_APPLY_SETTINGS_TAB',
COMPANY_LISTING_IMPERSONATE_USER_REQUESTS_TAB :'COMPANY/COMPANY_LISTING_IMPERSONATE_USER_REQUESTS_TAB',
COMPANY_LISTING_ROLE_MANAGEMENT_TAB :'COMPANY/COMPANY_LISTING_ROLE_MANAGEMENT_TAB',
COMPANY_LISTING_ROLE_REPORTS_TAB :'COMPANY/COMPANY_LISTING_ROLE_REPORTS_TAB',
COMPANY_LISTING_SEARCH_PAGE_NO :'COMPANY/COMPANY_LISTING_SEARCH_PAGE_NO',
COMPANY_LISTING_NEXT_PAGE :'COMPANY/COMPANY_LISTING_NEXT_PAGE',
COMPANY_LISTING_LAST_PAGE :'COMPANY/COMPANY_LISTING_LAST_PAGE',
COMPANY_LISTING_FIRST_PAGE :'COMPANY/COMPANY_LISTING_FIRST_PAGE',
COMPANY_LISTING_PREVIOUS_PAGE :'COMPANY/COMPANY_LISTING_PREVIOUS_PAGE',
COMPANY_CREATEPOPUP_COMPANY: 'COMPANY/COMPANY_CREATEPOPUP_COMPANY',

    
    COMPANY_ACTIVE_DEACTIVE_DATA: "COMPANY018224",
    COMPANY_EDIT_NAME: "COMPANY232914"


}