module.exports = {
    APPROVE_ACTION: "AllApproval/APPROVE_ACTION",
    APPROVE_SPO_POPUP_COMMENT_TEXTAREA: "AllApproval/APPROVE_SPO_POPUP_COMMENT_TEXTAREA",
    APPROVE_SPO_APPROVE_BUTTON: "AllApproval/APPROVE_SPO_POPUP_APPROVE_BUTTON",
    APPROVAL_LISTING_SPO_STATUS: "AllApproval/APPROVAL_LISTING_SPO_STATUS",
    APPROVE_SPO_POPUP_APPROVE_BUTTON: "AllApproval/APPROVE_SPO_POPUP_APPROVE_BUTTON",
}