package com.zycus.automation.eproc.pageobjects.pages.settings.cusomizesettings;

import org.apache.log4j.Logger;
import org.openqa.selenium.WebDriver;

import com.zycus.automation.eproc.pageobjects.pages.FactoryPage;
import com.zycus.automation.exception.ActionBotException;
import com.zycus.automation.exception.FactoryMethodException;

/**
 * @author ankita.sawant
 */
public class PageCustomizeSettings
{

	static Logger logger = Logger.getLogger(PageCustomizeSettings.class);

	public static void clickOnAllowEditAutogeneratedSettingsNo(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnAllowEditAutogeneratedSettingsNo(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnAllowEditAutogeneratedSettingsNo " + e, e);
		}

	}

	public static void clickOnAllowEditAutogeneratedSettingsYes(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnAllowEditAutogeneratedSettingsYes(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnAllowEditAutogeneratedSettingsYes " + e, e);
		}

	}

	public static void clickOnApprovalWorkflowLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnApprovalWorkflowLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnApprovalWorkflowLink " + e, e);
		}

	}

	public static void clickOnBuyersDeskLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnBuyersDeskLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnBuyersDeskLink " + e, e);
		}

	}

	public static void clickOnCatalogLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnCatalogLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnCatalogLink " + e, e);
		}

	}

	public static void clickOnCentralReceivingLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnCentralReceivingLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnCentralReceivingLink " + e, e);
		}

	}

	public static void clickOnCostBookingLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnCostBookingLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnCostBookingLink " + e, e);
		}

	}

	public static void clickOnDeliverySettingsLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnDeliverySettingsLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnDeliverySettingsLink " + e, e);
		}

	}

	public static void clickOnDesktopReceivingLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnDesktopReceivingLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnDesktopReceivingLink " + e, e);
		}

	}

	public static void clickOnDocumentInformationLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnDocumentInformationLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnDocumentInformationLink " + e, e);
		}

	}

	public static void clickOnEformLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnEformLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnEformLink " + e, e);
		}

	}

	public static void clickOnGeneralSettingsLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnGeneralSettingsLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnGeneralSettingsLink " + e, e);
		}

	}

	public static void clickOnIntegrationLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnIntegrationLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnIntegrationLink " + e, e);
		}

	}

	public static void clickOnInvoicesLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnInvoicesLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnInvoicesLink " + e, e);
		}
	}

	public static void clickOnMasterDataLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnMasterDataLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnMasterDataLink " + e, e);
		}

	}

	public static void clickOnMatchingLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnMatchingLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnMatchingLink " + e, e);
		}

	}

	public static void clickOnOtherNotificationsLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnOtherNotificationsLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnOtherNotificationsLink " + e, e);
		}

	}

	public static void clickOnPaymentsLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnPaymentsLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnPaymentsLink " + e, e);
		}

	}

	public static void clickOnPCardLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnPCardLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnPCardLink " + e, e);
		}

	}

	public static void clickOnProjectCustomizeLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnProjectCustomizeLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnProjectCustomizeLink " + e, e);
		}

	}

	public static void clickOnPurchaseOrderLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnPurchaseOrderLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnPurchaseOrderLink " + e, e);
		}

	}

	public static void clickOnReceiptsLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnReceiptsLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnReceiptsLink " + e, e);
		}

	}

	public static void clickOnReceivingGeneralSettingsLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnReceivingGeneralSettingsLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnReceivingGeneralSettingsLink " + e, e);
		}

	}

	public static void clickOnRequisitionLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnRequisitionLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnRequisitionLink " + e, e);
		}

	}

	public static void clickOnSaveButtom(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnSaveButtom(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnSaveButtom " + e, e);
		}

	}

	public static void clickOnSupplierNetworkLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnSupplierNetworkLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnSupplierNetworkLink " + e, e);
		}

	}

	public static void clickOnSupplierOnBoardingLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnSupplierOnBoardingLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnSupplierOnBoardingLink " + e, e);
		}

	}

	public static void clickOnToleranceLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnToleranceLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnToleranceLink " + e, e);
		}

	}

	public static void clickOnWorkflowLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnWorkflowLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnWorkflowLink " + e, e);
		}

	}

	public static boolean isAllowEditingAutogeneratedPoNoYes(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.isAllowEditingAutogeneratedPoNoYes(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method isAllowEditingAutogeneratedPoNoYes " + e, e);
		}
		return false;

	}

	public static boolean isAllowUserToChangeLevelToUsePoNoFormat(WebDriver driver, String testCaseName, String text) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			return customizeSettings.isAllowUserToChangeLevelToUsePoNoFormat(driver, testCaseName, text);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method isAllowUserToChangeLevelToUsePoNoFormat " + e, e);
		}
		return false;

	}

	public static boolean isAllowUserToChangePoNoFormat(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.isAllowUserToChangePoNoFormat(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method isAllowUserToChangePoNoFormat " + e, e);
		}
		return false;

	}

	public static boolean isAllowUserToChangePoSeqEndAtFormat(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.isAllowUserToChangePoSeqEndAtFormat(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method isAllowUserToChangePoSeqEndAtFormat " + e, e);
		}
		return false;

	}

	public static boolean isAllowUserToChangePoSeqStartAtFormat(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.isAllowUserToChangePoSeqStartAtFormat(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method isAllowUserToChangePoSeqStartAtFormat " + e, e);
		}
		return false;

	}

	public static boolean isReplyToAddressFieldPresent(WebDriver driver, String testCaseName, String to) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			return customizeSettings.isReplyToAddressFieldPresent(driver, testCaseName, to);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method isReplyToAddressFieldPresent " + e, e);
		}
		return false;

	}

	public static void clickOnBackLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		{
			try
			{
				IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
				customizeSettings.clickOnBackLink(driver, testCaseName);
			}
			catch (FactoryMethodException e)
			{
				logger.error("Factory Method Exception in method clickOnBackLink " + e, e);
			}

		}
	}

	public static void clickOnReqiuredByDateYes(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnReqiuredByDateYes(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnReqiuredByDateYes " + e, e);
		}

	}

	public static void clickOnReqiuredByDateNo(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnReqiuredByDateNo(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnReqiuredByDateNo " + e, e);
		}

	}

	public static void clickOnCustomizeLinkMasterData(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnCustomizeLinkMasterData(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnCustomizeLinkMasterData " + e, e);
		}
	}

	public static void clickOnGLRulesMap(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnGLRulesMap(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnCustomizeLinkMasterData " + e, e);
		}
	}

	public static void clickOnControlLink(WebDriver driver, String testCaseName) throws ActionBotException
	{
		try
		{
			IPageCustomizeSettings customizeSettings = FactoryPage.getInstanceOfIPageCustomizeSettings();
			customizeSettings.clickOnControlLink(driver, testCaseName);
		}
		catch (FactoryMethodException e)
		{
			logger.error("Factory Method Exception in method clickOnCostBookingLink " + e, e);
		}

	}

}
