module.exports={

    CART_ITEM_TABLE : "Cart/CART_ITEM_TABLE",
    CHECKOUT_BUTTON : "Cart/CHECKOUT_BUTTON",
    DELETE_ALL_ITEMS_BUTTON : "Cart/DELETE_ALL_ITEMS_BUTTON",
    ITEM_DELETE_SUCCESS_MSG : "Cart/ITEM_DELETE_SUCCESS_MSG",
    CONFIRM_POPUP_YES_BUTTON : "Cart/CONFIRM_POPUP_YES_BUTTON",
};
