module.exports = {
    supplierField: 'commonElements/SUPPLIER_FIELD',
    nextBtn: 'commonElements/NEXT_BTN', 
    addressField: 'commonElements/ADDRESS_FIELD',
    firstAddress: 'commonElements/FIRST_ADDRESS',
    remitAddressField: 'commonElements/REMIT_ADDRESS_FIELD',
    firstRemitAddress: 'commonElements/FIRST_REMIT_ADDRESS',
    requesterField: 'commonElements/REQUESTER_FIELD',
    companyField: 'commonElements/COMPANY_FIELD',
    businessUnitField: 'commonElements/BUSINESS_UNIT_FIELD',
    locationField: 'commonElements/LOCATION_FIELD',
    addSplitBtn: 'commonElements/ADD_SPLIT_BTN',
    buField: 'commonElements/BU_FIELD',
    costCenterField: 'commonElements/COST_CENTER_FIELD',
    percentageField: 'commonElements/PERCENTAGE_FIELD',
    addLineItemBtn: 'commonElements/ADD_LINE_ITEM_BTN',
    itemNameField: 'commonElements/ITEM_NAME_FIELD',
    categoryField: 'commonElements/CATEGORY_FIELD',
    qtyOrAmtField: 'commonElements/QTY_OR_AMT_FIELD',
    uomField: 'commonElements/UOM_FIELD',
    priceField: 'commonElements/PRICE_FIELD',
    nextBtn: 'commonElements/NEXT_BTN',
    costBookingDetailsLink: 'commonElements/COST_BOOKING_DETAILS_LINK',
    glAccountField: 'commonElements/GL_ACCOUNT_FIELD',
    saveBtn: 'commonElements/SAVE_BTN',
    submitBtn: 'commonElements/SUBMIT_BTN',
}