module.exports={

    RECEIPT_TAB_PO_VIEW:'ViewPO/ReceiptTab/RECEIPT_TAB',
    CREATE_BUTTON: 'ReceiptListing/CREATE_BUTTON',
    CREATE_RECEIPT_BUTTON: 'ReceiptListing/CREATE_RECEIPT_BUTTON',
    SECONDARY_ACTION_SELECTION: 'ReceiptListing/SECONDARY_ACTION_SELECTION',
    DELETE_ACTION: 'ReceiptListing/DELETE_ACTION',
    DELETE_ACTION_CONFIRMATION_YES: 'ReceiptListing/DELETE_ACTION_CONFIRMATION_YES',
    STATUS: 'ReceiptListing/STATUS',
    FIRST_ITEM_SELECTION_CHECKBOX: 'ReceiptPage/FIRST_ITEM_SELECTION_CHECKBOX',
    ALL_ITEM_SELECTION_CHECKBOX: 'ReceiptPage/ALL_ITEM_SELECTION_CHECKBOX',
    SAVE_AS_DRAFT_BUTTON: 'ReceiptPage/SAVE_AS_DRAFT_BUTTON',
    SUBMIT_BUTTON: 'ReceiptPage/SUBMIT_BUTTON',
    CONFIRMATION_POPUP_YES: 'ReceiptPage/CONFIRMATION_POPUP_YES',
    SEARCH_BUTTON: 'POListing/SEARCH_FIELD',
    SEARCH_PO_NUMBER: 'POListing/SEARCH_PO_NUMBER',
    RECEIVED_QTY: 'ReceiptPage/RECEIVED_QTY',
    APPROVED_QTY: 'ReceiptPage/APPROVED_QTY',
    PO_VIEW: 'ReceiptPage/PO_VIEW',


}