export let Login_TMSObj ={

    ExportUserData: 'Login/MENUSOPTIONS',
    EMAILADDRESS_TEXTBOX: "Login/EMAIL_ADDRESS_TEXTBOX",
    PASSWORD_TEXTBOX: 'Login/PASSWORD_TEXTBOX',
    LOGIN_BUTTON: 'Login/LOGIN_BUTTON',
    OTP_Field: 'Login/OTP_Field',
    MENUSOPTIONS: 'Login/MENUSOPTIONS',
    DD_HOME:'HOME/home',
    TMS_PRODUCT: 'HOME/TMSMenu',
    TMS_LOGOUT: 'HOME/LOGOUT',
    USER_ICON: "Login/USER_ICON",
    LOGOUT_BUTTON: "Login/LOGOUT_BUTTON",
    LOGOUT_CONFIRMATION_YES_BUTTON: "Login/LOGOUT_CONFIRMATION_YES_BUTTON",
    LOGOUT_CONFIRMATION_POPUP: "Login/LOGOUT_CONFIRMATION_POPUP",
    LOADING_SPINNER: "CommonKeyword/LOADING_SPINNER",
    TMS_TMSSubmenu:"HOME/TMS_TMSSubmenu",
    Quick_Link_button:"HOME/Quick_Link_button",
    Customize_button:"HOME/Customize_button",
    Search_Field:"HOME/Search_Field",
    Clickon_TMS_button:"HOME/Clickon_TMS_button",
    Clickon_Apply_button:"HOME/Clickon_Apply_button",
    Quick_TMS_Menu:"HOME/Quick_TMS_Menu",
    RESENDOTP_BUTTON:"Login/RESENDOTP_BUTTON",
}