module.exports = {

    MY_REQ_NAV: "MyReq/MY_REQ_NAV",
    GUIDE_ME: "MyReq/GUIDE_ME",
    START_BTN: "GuideMe/START_BTN",
    GENERIC_RADIO_BTN: "GuideMe/GENERIC_RADIO_BTN",
    GENERIC_NEXT_BTN:"GuideMe/GENERIC_NEXT_BTN",
    HR_BTN:"GuideMe/HR_BTN",
    INFO_TEXTAREA:"GuideMe/INFO_TEXTAREA",
    HR_NEXT_BTN:"GuideMe/HR_NEXT_BTN"

 

}