module.exports={
    FILTER_BUTTON: "BuyersDeskListing/FILTER_BUTTON",
    SEARCH_REQUISITION_NUMBER: "BuyersDeskListing/SEARCH_REQUISITION_NUMBER",
    FILTER_APPLY_BUTTON: "BuyersDeskListing/FILTER_APPLY_BUTTON",
    REQUISITION_NUMBER_LISTING: "BuyersDeskListing/REQUISITION_NUMBER_LISTING",
    REQUISITION_NAME_LISTING:"BuyersDeskListing/REQUISITION_NAME_LISTING",
    PURCHASE_AMOUNT_MIN_INPUT:"BuyersDeskListing/PURCHASE_AMOUNT_MIN_FIELD",
    PURCHASE_AMOUNT_MAX_INPUT:"BuyersDeskListing/PURCHASE_AMOUNT_MAX_INPUT",
    PURCHASE_AMOUNT_FILTER:"BuyersDeskListing/PURCHASE_AMOUNT_FILTER"
}