module.exports={
    FILTER_BUTTON: "BuyersDeskListing/FILTER_BUTTON",
    SEARCH_REQUISITION_NUMBER: "BuyersDeskListing/SEARCH_REQUISITION_NUMBER",
    FILTER_APPLY_BUTTON: "BuyersDeskListing/FILTER_APPLY_BUTTON",
    REQUISITION_NUMBER_LISTING: "BuyersDeskListing/REQUISITION_NUMBER_LISTING",
    REQUISITION_NAME_LISTING:"BuyersDeskListing/REQUISITION_NAME_LISTING",
    APPLY_STATUS_BUTTON:"BuyersDeskListing/APPLY_STATUS_BUTTON",
    BUYER_NAME_LISTING:"BuyersDeskListing/BUYER_NAME_LISTING",
    ASSIGNED_BUYER_FILTER: "BuyersDeskListing/ASSIGNED_BUYER_FILTER",
    TOTAL_PAGES: "BuyersDeskListing/TOTAL_PAGES",
    ASSIGNED_BUYER: "BuyersDeskListing/ASSIGNED_BUYER",
    REQUISITION_CHECKBOX: "BuyersDeskListing/REQUISITION_CHECKBOX",
    CONVERT_PO_BUTTON: "BuyersDeskListing/CONVERT_PO_BUTTON"
}