module.exports={
    FILTER_BUTTON: "BuyersDeskListing/FILTER_BUTTON",
    SEARCH_REQUISITION_NUMBER: "BuyersDeskListing/SEARCH_REQUISITION_NUMBER",
    FILTER_APPLY_BUTTON: "BuyersDeskListing/FILTER_APPLY_BUTTON",
    REQUISITION_NUMBER_LISTING: "BuyersDeskListing/REQUISITION_NUMBER_LISTING",
    REQUISITION_NAME_LISTING:"BuyersDeskListing/REQUISITION_NAME_LISTING"
}