module.exports={

    createPOButton: "//dew-listing-create//button[@class='btn primary']",
    standardPOButton : "(//dew-modal[@class='show modal fade']//dew-modal-body//button[@class='btn primary'])[1]",
    spinner : "//dew-spinner[@class='dew-spinner']",
    poNumberTextbox : "#purchaseOrderNumber-field",
    poDescriptionTextbox : "#purchaseOrderDescription-field",
    purchaseTypeDropdown : "//dew-select[@id='headerPurchaseType-field']//dew-dropdown-trigger[contains(@class,'select-dropdown')]",
    purchaseTypeValue : "//div[@class='dropdown-item text-truncate text-14']",
    supplierNameTextbox :  "//dew-autocomplete-supplier[@id='supplierId-field']//input",
    supplierAddressTextbox : "//dew-autocomplete-supplier-address//input[@formcontrolname='supplierAddressObj']",
    paymentTermDropdown : "//dew-input-container[@id='paymentTermId-field']//dew-dropdown-trigger[contains(@class,'select')]",
    deliveryTermDropdown : "//dew-input-container[@id='deliveryTermCode-field']//dew-dropdown-trigger[contains(@class,'select')]",
    currencyTextbox : "//dew-input-container[@id='suppCurrency-field']//dew-typeahead//input[@aria-label='Supplier Currency']",
    buyerTextbox : "//div[@formgroupname='buyerInformationForm']//input[@aria-label='Buyer Name']",
    TAB_NAME_LIST: "//div[contains(@class,'tab-links-wrapper')]//dew-default-tab-head ",
    COST_ALLOCATION_TAB: "//dew-default-tab-head[contains(text(),'Cost Allocation')]",
    ASSIGN_COST_PROJECT_NO_RADIO_BUTTON: "//label[@for='assignPurchaseCostNo']",
    BOOK_COST_TO_SINGLE_MULTIPLE_COST_CENTER_RADIO_BUTTON: "//label[@for='singleOrMultipleCC']",
    COST_CENTER_INPUT_FIELD: "//input[@formcontrolname='costCentre']",
    ADD_LINE_ITEM_BUTTON: "//button[@aria-label='Add Line Item']",
    ITEM_NAME_INPUT: "//eproc-line-item-details//input[contains(@class,'form-control')]",
    FIRST_ITEMNAME_OPTION: "//div[contains(@class,'suggestion-menu-row')]",
    GLACCOUNT: "//input[@formcontrolname='generalLedger']",
    COSTBOOKING_SAVE_BUUTON: "//footer//button[contains(@class,'btn primary')]",
    REMOVE_ALL_TAXES_BUTTON: "//div[@class='removeTaxbtn']//button[@aria-label='Remove All Taxes']",
    SUBMIT_PO_BUTTON: "//footer//button[@aria-label='Submit PO']",

}