module.exports = {
    SEARCH_TEXTBOX: "PoListing/SEARCH_TEXTBOX",
    REQUISITION_LISTING_PAGE: "RequisitionListing/REQUISITION_LISTING_PAGE",
    REQUISITION_STATUS: "RequisitionListing/REQUISITION_STATUS",
    EDIT_ACTION: "RequisitionListing/EDIT_ACTION",
    DELETE_CONFIRM_POPUP: "RequisitionListing/DELETE_CONFIRM_POPUP",
    DELETE_CONFIRM_YES_BUTTON: "RequisitionListing/DELETE_CONFIRM_YES_BUTTON",
    DELETE_SUCCESS_MESSAGE: "RequisitionListing/DELETE_SUCCESS_MESSAGE",
    DELETE_SUCCESS_MESSAGE_OK_BUTTON: "RequisitionListing/DELETE_SUCCESS_MESSAGE_OK_BUTTON",
    NO_RECORDS_FOUND: "RequisitionListing/NO_RECORDS_FOUND",
    CLOSE_REQUISITION_POPUP: "RequisitionListing/CLOSE_REQUISITION_POPUP",
    CLOSE_REQUISITION_BUTTON: "RequisitionListing/CLOSE_REQUISITION_BUTTON",
};