export let prop= {
            "url": "https://dewdrops-qcvw.zycus.net/home/#/auth",
            "SETUP": "QC",
            "TENANT": "SpaceX",
            "browser": "chrome",
            "host": "127.0.0.1",
            "restart": "false",
            "port": 4444,
            "windowSize": "maximize",
            "stepFilePath": "./steps_file",
            "projectName": "BDD_UI_Automation",
            "DEFAULT_WAIT": "2",
            "DEFAULT_LOW_WAIT": 15,
            "DEFAULT_MEDIUM_WAIT": 20,
            "DEFAULT_HIGH_WAIT": 35,
            "CONDITIONAL_WAIT": 50,
            "DBhost": "192.168.5.221",
            "DBdatabase": "Gauge_schema",
            "DBuser": "gauge.poc",
            "DBpassword": "gauge@123",
            "username": "auto.staging1@zycus.com",
            "password": "NuEuOiBuCeFe&40",
            "testdataTable": "TestData_eproc",
            "uiElementTable": "Dev_eProc_UI_Elements",
            "UserTable":"eProc_credentials",
            "dir":" ",
            "executionStartTime":" ",
            "enableInfraDetailsScript":false,
            "email_address": "dd.autouser@zycus.com",
            "user_password": "e5U%FP6V",
            "email_address1": "ranjit.more@zycus.com",
            "user_password1": "rmz@112020",
            "productKey":"TMS",    
            "productName":"TMS",    
            "xrayFeatureFilePath":"src/TMS/features/Earth",
            "sprintName": "Sprint 150",
            "sprintBoardId": "781",
            "releaseTrain": "Earth"
        }
        
    
