export let ProductObj=
{
    ComptoEdit: "QMS Sanity US",
    ProdtoEdit: "0Ru_auto",
    
    // ProdTab: "//a[text()='Products']",
    ProdTab: "PRODUCT/ProdTab",
    // AddNewProd: "//a[@title='Add New Product']",
    // ProdName:"//input[@id='product_Name']",
    // WhiteListedBrowser: "//input[@id='white_Listed_browsers']",
    // WhiteListedBrowserVal: "Mozilla",
    // BlackListedBrowser: "//input[@id='black_listed_browsers']",
    // BlackListedBrowserVal: "Safari 7+",
    // UnsupportedBrowser: "//input[@id='unsupported_browsers']",
    // UnsupportedBrowserVal: "Safari 7+",
    // DefaultBehaviourDD: "//select[@name='default_behaviour']",
    // DefaultBehaviour: "//select[@name='default_behaviour']/option[text()='UNSUPPORTED']",
    // SupportedBrowserTemp:"//textarea[@name='supported_browser_template']",
    // SupportedBrowserVal: "IE 10+, Edge 10+, Firefox 26+, Chrome 35+",
    // SaveNContinue: "//input[@title='Save and Continue']",
    AddNewProd: "PRODUCT/AddNewProd",
    ProdName:"PRODUCT/ProdName",
    WhiteListedBrowser: "PRODUCT/WhiteListedBrowser",
    WhiteListedBrowserVal: "Mozilla",
    BlackListedBrowser: "PRODUCT/BlackListedBrowser",
    BlackListedBrowserVal: "Safari 7+",
    UnsupportedBrowser: "PRODUCT/UnsupportedBrowser",
    UnsupportedBrowserVal: "Safari 7+",
    DefaultBehaviourDD: "PRODUCT/DefaultBehaviourDD",
    DefaultBehaviour: "PRODUCT/DefaultBehaviour",
    SupportedBrowserTemp:"PRODUCT/SupportedBrowserTemp",
    SupportedBrowserVal: "IE 10+, Edge 10+, Firefox 26+, Chrome 35+",
    SaveNContinue: "PRODUCT/SaveNContinue",
    AddNewActGroup: "PRODUCT/AddNewActGroup",
    AGName: "PRODUCT/AGName",
    PopUpSave: "PRODUCT/PopUpSave",
    PopUpClose: "PRODUCT/PopUpClose",
    
    AddNewActivities: "PRODUCT/AddNewActivities",
    ActName: "PRODUCT/ActName",
    EditActName: "PRODUCT/EditActName",
    ActURL: "PRODUCT/ActURL",
    EditActURL:"PRODUCT/EditActURL",
    ActURLVal: "PRODUCT/ActURLVal",
    ActCode: "PRODUCT/ActCode",
    NonSysAct: "PRODUCT/NonSysAct",
    SaveActBtn: "PRODUCT/SaveActBtn",
    PopUpCancel_Act: "PRODUCT/PopUpCancel_Act",
    EditPopUpCancel_Act:"PRODUCT/EditPopUpCancel_Act",
    DoneBtn: "PRODUCT/DoneBtn",
    EditSaveActBtn:"PRODUCT/EditSaveActBtn",
    
    EditComp: "PRODUCT/EditComp",
    EditProdAllocation: "PRODUCT/EditProdAllocation",
    
    // Company: "//a[@id='COMPANY']",
    // CompSearch: "//input[@id='eventSearchText']",
    // GoBtn: "//input[@value='Go']",
    // SearchRes: "//td/label[text()='ZCS']",
    Company: "PRODUCT/Company",
    CompSearch: "PRODUCT/CompSearch",
    GoBtn: "PRODUCT/GoBtn",
    SearchRes: "PRODUCT/SearchRes",
    
    //EditProd: `//td[text()="${ProdtoEdit}"]/following-sibling::td/label`,
    // x: "//td[text()='0Ru_auto']/following-sibling::td/label",
    // EditProdInfo: "//span[text()='Product Information']/following-sibling::label[text()='Edit']",
    // UpdateNSaveBtn: "//input[@title='Update and Continue']",
    x: "PRODUCT/x",
    EditProdInfo: "PRODUCT/EditProdInfo",
    UpdateNSaveBtn: "PRODUCT/UpdateNSaveBtn",
    
    // NextPage: "//li[@class='next']",
    // ToCheck: "//td[text()='Black Listed Browsers']/following-sibling::td",
    NextPage: "PRODUCT/NextPage",
    ToCheck: "PRODUCT/ToCheck",
}