module.exports = {
    addInvoiceBtn: 'invoiceHomePage/ADD_INVOICE_BTN',
    searchField: 'invoiceHomePage/SEARCH_FIELD',
    statusFilterIcon: 'invoiceHomePage/STATUS_FILTER_ICON',
    applyBtn: 'invoiceHomePage/APPLY_BTN',
    invoiceFilterIcon: 'invoiceHomePage/INVOICE_FILTER_ICON',
    saveViewBtn: 'invoiceHomePage/SAVE_VIEW_BTN',
    viewNameField: 'invoiceHomePage/VIEW_NAME_FIELD',
    saveBtn: 'invoiceHomePage/SAVE_BTN',
    viewMenuBtn: 'invoiceHomePage/VIEW_MENU_BTN',
    deleteViewBtn: 'invoiceHomePage/DELETE_VIEW_BTN',
    deleteBtn: 'invoiceHomePage/DELETE_BTN',
    supplierFilterIcon: 'invoiceHomePage/SUPPLIER_FILTER_ICON',
    supplierSeacrhField: 'invoiceHomePage/SUPPLIER_SEARCH_FIELD',
    referenceNumFilterIcon: 'invoiceHomePage/REFERENCE_FILTER_ICON',
    referenceNumSearchField: 'invoiceHomePage/REFERENCE_SEARCH_FIELD',
}