/**
 * 
 */
package com.zycus.automation.bo;

/**
 * @author ankita.sawant
 *
 */
public class PurchaseOrderSettings
{
	private String	poNoFormat;
	private int		seqNoStartsAt;
	private int		seqNoEndsAt;
	private String	poNameForAutoGeneratedOrders;
	private String	limitationOfDisplayOfPO;
	private boolean	autoGenerateLineItemNumbers							= true;
	private boolean	modifyItemClassificationCode						= true;
	private boolean	allowManualOrdersReleasedWithoutDeliveryDate		= true;
	private boolean	releaseOrdersImmediately							= true;
	private int		releaseOrderDays;
	private boolean	automaticallyGenerateOrders							= false;
	private String	nextAction;
	private String	defaultBuyerForAutoPO								= null;
	private String	BPOAuthorizationType								= null;
	private boolean	sendBPOToSupplierWithRelease						= false;
	private boolean	allowEmailingPOToContactsOtherThanSuppliersContact	= true;
	private boolean	allowEmailingPOToUsersOutsideCompany				= true;
	private boolean	allowUsersToChangeDefaultSupplierCurrency			= true;
	private boolean	allowUsersToChangeDefaultSupplierPaymentTerms		= true;
	private boolean	allowUsersToChangeDefaultSupplierDeliveryTerms		= true;
	private boolean	allowEditingAutoGeneratedPONO						= true;
	private boolean	allowBuyersToAddNewItemsToExistingPO				= true;

	public boolean isAllowEmailingPOToContactsOtherThanSuppliersContact()
	{
		return allowEmailingPOToContactsOtherThanSuppliersContact;
	}

	public void setAllowEmailingPOToContactsOtherThanSuppliersContact(boolean allowEmailingPOToContactsOtherThanSuppliersContact)
	{
		this.allowEmailingPOToContactsOtherThanSuppliersContact = allowEmailingPOToContactsOtherThanSuppliersContact;
	}

	public boolean isAllowEmailingPOToUsersOutsideCompany()
	{
		return allowEmailingPOToUsersOutsideCompany;
	}

	public void setAllowEmailingPOToUsersOutsideCompany(boolean allowEmailingPOToUsersOutsideCompany)
	{
		this.allowEmailingPOToUsersOutsideCompany = allowEmailingPOToUsersOutsideCompany;
	}

	public boolean isAllowUsersToChangeDefaultSupplierPaymentTerms()
	{
		return allowUsersToChangeDefaultSupplierPaymentTerms;
	}

	public void setAllowUsersToChangeDefaultSupplierPaymentTerms(boolean allowUsersToChangeDefaultSupplierPaymentTerms)
	{
		this.allowUsersToChangeDefaultSupplierPaymentTerms = allowUsersToChangeDefaultSupplierPaymentTerms;
	}

	public boolean isAllowUsersToChangeDefaultSupplierDeliveryTerms()
	{
		return allowUsersToChangeDefaultSupplierDeliveryTerms;
	}

	public void setAllowUsersToChangeDefaultSupplierDeliveryTerms(boolean allowUsersToChangeDefaultSupplierDeliveryTerms)
	{
		this.allowUsersToChangeDefaultSupplierDeliveryTerms = allowUsersToChangeDefaultSupplierDeliveryTerms;
	}

	public boolean isAllowEditingAutoGeneratedPONO()
	{
		return allowEditingAutoGeneratedPONO;
	}

	public void setAllowEditingAutoGeneratedPONO(boolean allowEditingAutoGeneratedPONO)
	{
		this.allowEditingAutoGeneratedPONO = allowEditingAutoGeneratedPONO;
	}

	public boolean isAllowBuyersToAddNewItemsToExistingPO()
	{
		return allowBuyersToAddNewItemsToExistingPO;
	}

	public void setAllowBuyersToAddNewItemsToExistingPO(boolean allowBuyersToAddNewItemsToExistingPO)
	{
		this.allowBuyersToAddNewItemsToExistingPO = allowBuyersToAddNewItemsToExistingPO;
	}

	public String getBPOAuthorizationType()
	{
		return BPOAuthorizationType;
	}

	public void setBPOAuthorizationType(String bPOAuthorizationType)
	{
		BPOAuthorizationType = bPOAuthorizationType;
	}

	public boolean isSendBPOToSupplierWithRelease()
	{
		return sendBPOToSupplierWithRelease;
	}

	public void setSendBPOToSupplierWithRelease(boolean sendBPOToSupplierWithRelease)
	{
		this.sendBPOToSupplierWithRelease = sendBPOToSupplierWithRelease;
	}

	public boolean isAllowUsersToChangeDefaultSupplierCurrency()
	{
		return allowUsersToChangeDefaultSupplierCurrency;
	}

	public void setAllowUsersToChangeDefaultSupplierCurrency(boolean allowUsersToChangeDefaultSupplierCurrency)
	{
		this.allowUsersToChangeDefaultSupplierCurrency = allowUsersToChangeDefaultSupplierCurrency;
	}

	public String getDefaultBuyerForAutoPO()
	{
		return defaultBuyerForAutoPO;
	}

	public void setDefaultBuyerForAutoPO(String defaultBuyerForAutoPO)
	{
		this.defaultBuyerForAutoPO = defaultBuyerForAutoPO;
	}

	public String getPoNoFormat()
	{
		return poNoFormat;
	}

	public void setPoNoFormat(String poNoFormat)
	{
		this.poNoFormat = poNoFormat;
	}

	public int getSeqNoStartsAt()
	{
		return seqNoStartsAt;
	}

	public void setSeqNoStartsAt(int seqNoStartsAt)
	{
		this.seqNoStartsAt = seqNoStartsAt;
	}

	public int getSeqNoEndsAt()
	{
		return seqNoEndsAt;
	}

	public void setSeqNoEndsAt(int seqNoEndsAt)
	{
		this.seqNoEndsAt = seqNoEndsAt;
	}

	public String getPoNameForAutoGeneratedOrders()
	{
		return poNameForAutoGeneratedOrders;
	}

	public void setPoNameForAutoGeneratedOrders(String poNameForAutoGeneratedOrders)
	{
		this.poNameForAutoGeneratedOrders = poNameForAutoGeneratedOrders;
	}

	public String getLimitationOfDisplayOfPO()
	{
		return limitationOfDisplayOfPO;
	}

	public void setLimitationOfDisplayOfPO(String limitationOfDisplayOfPO)
	{
		this.limitationOfDisplayOfPO = limitationOfDisplayOfPO;
	}

	public boolean isAutoGenerateLineItemNumbers()
	{
		return autoGenerateLineItemNumbers;
	}

	public void setAutoGenerateLineItemNumbers(boolean autoGenerateLineItemNumbers)
	{
		this.autoGenerateLineItemNumbers = autoGenerateLineItemNumbers;
	}

	public boolean isModifyItemClassificationCode()
	{
		return modifyItemClassificationCode;
	}

	public void setModifyItemClassificationCode(boolean modifyItemClassificationCode)
	{
		this.modifyItemClassificationCode = modifyItemClassificationCode;
	}

	public boolean isAllowManualOrdersReleasedWithoutDeliveryDate()
	{
		return allowManualOrdersReleasedWithoutDeliveryDate;
	}

	public void setAllowManualOrdersReleasedWithoutDeliveryDate(boolean allowManualOrdersReleasedWithoutDeliveryDate)
	{
		this.allowManualOrdersReleasedWithoutDeliveryDate = allowManualOrdersReleasedWithoutDeliveryDate;
	}

	public boolean isReleaseOrdersImmediately()
	{
		return releaseOrdersImmediately;
	}

	public void setReleaseOrdersImmediately(boolean releaseOrdersImmediately)
	{
		this.releaseOrdersImmediately = releaseOrdersImmediately;
	}

	public int getReleaseOrderDays()
	{
		return releaseOrderDays;
	}

	public void setReleaseOrderDays(int releaseOrderDays)
	{
		this.releaseOrderDays = releaseOrderDays;
	}

	public boolean isAutomaticallyGenerateOrders()
	{
		return automaticallyGenerateOrders;
	}

	public void setAutomaticallyGenerateOrders(boolean automaticallyGenerateOrders)
	{
		this.automaticallyGenerateOrders = automaticallyGenerateOrders;
	}

	public String getNextAction()
	{
		return nextAction;
	}

	public void setNextAction(String nextAction)
	{
		this.nextAction = nextAction;
	}

}
