module.exports={

    ITEM_SELECTION_CHECKBOX: 'ReturnNotePage/ITEM_SELECTION_CHECKBOX',
    QUANTITY: 'ReturnNotePage/QUANTITY',
    REASON_FOR_RETURN_DROPDOWN: 'ReturnNotePage/REASON_FOR_RETURN_DROPDOWN',
    REASON_FOR_RETURN_SELECTION: 'ReturnNotePage/REASON_FOR_RETURN_SELECTION',
    RETURN_METHOD_DROPDOWN: 'ReturnNotePage/RETURN_METHOD_DROPDOWN',
    RETURN_METHOD_SELECTION: 'ReturnNotePage/RETURN_METHOD_SELECTION',


}