export let CreateReportObj = {
    // CreateReportTab: "//a[text()='Reports']",
    // CreateRepBtn: "//label[@title='Create New Report']",
    // TabularRep: "//input[@value='1']",
    // NextBtn: "//input[@value='Next']",
    // SumReport: "//input[@value='1']",
    // S3Prod: "//input[@value='uac.Product_Name']",
    // S3UEmailId: "//input[@value='u.EMAIL_ADDRESS']",
    // S3Company: "//input[@value='c.ACTIVE']",
    // S3DomainUrl: "//input[@value='cd.domainurl']",
    // S3Manager: "//input[@value='umv.MANAGER_EMAIL_ADDRESS']",
    // S3UserUniqueId: "//input[@value='uui.UNIQUE_ID_VALUE']",
    // S6StartDate: "//input[@id='durationStartDate_RMS']",
    // StartDate: "12/12/2018",
    // S6EndDate: "//input[@id='durationEndDate_RMS']",
    // EndDate: "04/04/2020",
    // RunReport: "//input[@value='Run Report']",

    // UsersByRole: "//span[text()='List of users grouped by role name and role type per product']",
    // UsersListperProduct: "//span[text()='List of users per product']",
    // MatrixRep: "//span[text()='Matrix report detailing number of users in a role per product']",
    // CloseReport: "//input[@title='Close']",

    CreateReportTab: "REPORTS/CreateReportTab",
    CreateRepBtn: "REPORTS/CreateRepBtn",
    TabularRep: "REPORTS/TabularRep",
    NextBtn: "REPORTS/NextBtn",
    SumReport: "REPORTS/SumReport",
    S3Prod: "REPORTS/S3Prod",
    S3UEmailId: "REPORTS/S3UEmailId",
    S3Company: "REPORTS/S3Company",
    S3DomainUrl: "REPORTS/S3DomainUrl",
    S3Manager: "REPORTS/S3Manager",
    S3UserUniqueId: "REPORTS/S3UserUniqueId",
    S6StartDate: "REPORTS/S6StartDate",
    // StartDate: "12/12/2018",
    S6EndDate: "REPORTS/S6EndDate",
    // EndDate: "04/04/2020",
    RunReport: "REPORTS/RunReport",

    UsersByRole: "REPORTS/UsersByRole",
    UsersListperProduct: "REPORTS/UsersListperProduct",
    MatrixRep: "REPORTS/MatrixRep",
    CloseReport: "REPORTS/CloseReport",
    ReportExcelBtn: "REPORTS/ReportExcelBtn",
    ReportDownloadExcelBtn: "REPORTS/ReportDownloadExcelBtn",
    ReportDownloadPDFBtn: "REPORTS/ReportDownloadPDFBtn"
 
}