export let CreateUserObj = {

    Locator_displayName:'CREATEUSER/Locator_displayName',
    AddNewUser_btn:'CREATEUSER/AddNewUser_btn',
    Locator_lastName:'CREATEUSER/Locator_lastName',
    Locator_firstName:'CREATEUSER/Locator_firstName',
    Locator_emailaddress:'CREATEUSER/Locator_emailaddress',
    //Salutation_Locator:'CREATEUSER/Salutation_Locator',
    Salutation_Locator:"//select[@name='salutation']",
    //Designation_Locator:'CREATEUSER/Designation_Locator',
    Designation_Locator:"//select[@id='designation']",
    Org_level1_Locator:'CREATEUSER/Org_level1_Locator',
    Org_level2_Locator:'CREATEUSER/Org_level2_Locator',
    Org_costCenter_Locator:'CREATEUSER/Org_costCenter_Locator',
    Org_Location_Locator:'CREATEUSER/Org_Location_Locator',
    Org_dept_Locator:'CREATEUSER/Org_dept_Locator',
    //Maneger_Email_Locator:'CREATEUSER/Maneger_Email_Locator',
    Maneger_Email_Locator:"//input[@id='managerEmail']",
    purchaseLimit:'CREATEUSER/purchaseLimit',
    requisitionApprovalLimit:'CREATEUSER/requisitionApprovalLimit',
    invoiceApprovalLimit:'CREATEUSER/invoiceApprovalLimit',
    //approvalCurrency:'CREATEUSER/approvalCurrency',
    approvalCurrency: "//select[@name='approvalCurrency']",
    uniqueKeyTypexpath:'CREATEUSER/uniqueKeyTypexpath',
    uniqueKeyTypefieldxpath:'CREATEUSER/uniqueKeyTypefieldxpath',
    addbuttonxpath:'CREATEUSER/addbuttonxpath',
    Ctn_MainBtn:'CREATEUSER/Ctn_MainBtn',
    RoleSearchField:'CREATEUSER/RoleSearchField',
    RoleSearchBtn:'CREATEUSER/RoleSearchBtn',
    Role_checkbox:'CREATEUSER/Role_checkbox',
    Locator_ScopeNameSearchField:'CREATEUSER/Locator_ScopeNameSearchField',
    Locator_ScopeNameSearchbutton:'CREATEUSER/Locator_ScopeNameSearchbutton',
    Locator_ScopeNameSelectcheckbox:'CREATEUSER/Locator_ScopeNameSelectcheckbox',
    Locator_numberFormat:'CREATEUSER/Locator_numberFormat',
    Locator_defaultDateFormat:'CREATEUSER/Locator_defaultDateFormat',
    Locator_timeFormat:'CREATEUSER/Locator_timeFormat',
    Locator_defaultCurrency:'CREATEUSER/Locator_defaultCurrency',
    Locator_defaultLocale:'CREATEUSER/Locator_defaultLocale',
    Locator_ipsource:'CREATEUSER/Locator_ipsource',
    Locator_decimalPrecision:'CREATEUSER/Locator_decimalPrecision',
    EditUserBtn:'CREATEUSER/EditUserBtn',
    CopyUserBtn:'CREATEUSER/CopyUserBtn',

    DisplayNameTxt:'CREATEUSER/DisplayNameTxt',
    FN_Txt:'CREATEUSER/FN_Txt',
    LN_Text:'CREATEUSER/LN_Text',
    Email_Txt:'CREATEUSER/Email_Txt',
    
    UserInitials:'CREATEUSER/UserInitials',
    ReportingMgr:'CREATEUSER/ReportingMgr',
    ERPId:'CREATEUSER/ERPId',
    UserId:'CREATEUSER/UserId',
    EmpId:'CREATEUSER/EmpId',
    ContactNo:'CREATEUSER/ContactNo',
    LoginThroughZycusTrue:'CREATEUSER/LoginThroughZycusTrue',
    LoginThroughZycusFalse:'CREATEUSER/LoginThroughZycusFalse',
    SubmitBtn:'CREATEUSER/SubmitBtn',
    DefineBtn:'CREATEUSER/DefineBtn',
    CancelBtn:'CREATEUSER/CancelBtn',
    UpdateUserBtn:'CREATEUSER/UpdateUserBtn',
    BasicDetailsEditBtn:'CREATEUSER/BasicDetailsEditBtn',
    ProductDetailsEditBtn:'CREATEUSER/ProductDetailsEditBtn',
    Designation_Value: "myDesignation1",
    Maneger_Email_Value: "jyotizDoc406@spacex.com",
    Salutation_Value:"Mr",
    approvalCurrency_value: "Indian Rupee",
    UniqueERPIDEdit:"CREATEUSER/UniqueERPIDEdit",
    UniqueUserIDEdit:"CREATEUSER/UniqueUserIDEdit",
    UniqueEmployeeIDEdit:"CREATEUSER/UniqueEmployeeIDEdit",
    UniqueContactNoEdit:"CREATEUSER/UniqueContactNoEdit",
    UniqueERPIDEditNumber:"CREATEUSER/UniqueERPIDEditNumber",
    UniqueUserIDEditNumber:"CREATEUSER/UniqueUserIDEditNumber",
    UniqueEmployeeIDEditNumber:"CREATEUSER/UniqueEmployeeIDEditNumber",
    UniqueContactNoEditNumber:"CREATEUSER/UniqueContactNoEditNumber",
    UniqueERPIDEditSave:"CREATEUSER/UniqueERPIDEditSave",
    UniqueUserIDEditSave:"CREATEUSER/UniqueUserIDEditSave",
    UniqueEmployeeIDEditSave:"CREATEUSER/UniqueEmployeeIDEditSave",
    UniqueContactNoEditSave:"CREATEUSER/UniqueContactNoEditSave",
    RoleDetailsEditBtn:"CREATEUSER/RoleDetailsEditBtn",
    ScopeDetailsEditBtn:"CREATEUSER/ScopeDetailsEditBtn",
    PreferenceDetailsEditBtn:"CREATEUSER/PreferenceDetailsEditBtn",
}