module.exports = {
    SPO_BASIC_DETAILS_SECTION: "Basic details",
    SPO_BILLING_INFORMATION_SECTION: "Billing Information",
    SPO_SUPPLIER_DETAILS_SECTION: "Supplier Details",
    SPO_BUYER_AND_OTHER_INFORMATION_SECTION: "MST_Buyerandotherinformation",
    SPO_SHIPPING_DETAILS_SECTION: "Shipping Details",
    SPO_COST_ALLOCATION_SECTION: "Cost Allocation",
    SPO_CONTROL_SETTINGS_SECTION: "Control Settings",
    SPO_LINE_ITEMS_SECTION: "Line Items",
    SPO_TAXES_SECTION_SECTION: "Taxes",
    SPO_ADDITIONAL_DETAILS_SECTION: "Additional Details",
    RECALL_ACTION_MENU_OPTION: "Recall Approval Request",
    AUTO_GENERATED_COMMENT: "This is an auto generated comment",
    DRAFT_STATUS: "Draft",
    SEARCH_BY_DOC_NUMBER: "Search by doc number",
    SEARCH_BY_DOC_NAME_OR_DESCRIPTION: "Search by doc name or description",
    APPROVED_STATUS: "Approved",
    RELEASED_STATUS: "Released",
    CLOSE_ACTION_MENU_OPTION: "Close",
    CLOSED_STATUS: "Closed",
    SPO_VIEW_LINE_ITEMS_SECTION: "Line Items",
}