module.exports = {
    EMAIL_ADDRESS_GHOST_TEXTBOX: "Login/EMAIL_ADDRESS_GHOST_TEXTBOX",
    EMAIL_ADDRESS_TEXTBOX: "Login/EMAIL_ADDRESS_TEXTBOX",
    PASSWORD_GHOST_TEXTBOX: "Login/PASSWORD_GHOST_TEXTBOX",
    PASSWORD_TEXTBOX: "Login/PASSWORD_TEXTBOX",
    LOGIN_BUTTON: "Login/LOGIN_BUTTON",
    DDS_LOGIN_PAGE: "Login/DDS_LOGIN_PAGE",
    REQ_TABLE_OPTION_ICON: "OnlineStore/REQ_TABLE_OPTION_ICON",

}