module.exports = {
    RECALL_APPROVAL_REQUEST_COMMENTS_TEXTAREA: "PoListing/RECALL_APPROVAL_REQUEST_COMMENTS_TEXTAREA",
    RECALL_APPROVAL_REQUEST_RECALL_BUTTON: "PoListing/RECALL_APPROVAL_REQUEST_RECALL_BUTTON",
    RECALLED_SUCCESS_DONE_BUTTON: "PoListing/RECALLED_SUCCESS_DONE_BUTTON",
    PO_STATUS: "PoListing/PO_STATUS",
    PO_NUMBER_LINK: "PoListing/PO_NUMBER_LINK",
    ACTION_MENU_ICON: "PoListing/ACTION_MENU_ICON",
    SEARCH_TEXTBOX: "PoListing/SEARCH_TEXTBOX",
    CLOSE_PO_POPUP_COMMENTS_TEXTAREA: "PoListing/CLOSE_PO_POPUP_COMMENTS_TEXTAREA",
    CLOSE_PO_POPUP_CLOSE_PO_BUTTON: "PoListing/CLOSE_PO_POPUP_CLOSE_PO_BUTTON",
    EDIT_ACTION: "PoListing/EDIT_ACTION",
}