module.exports = {
    RECALL_APPROVAL_REQUEST_COMMENTS_TEXTAREA: "PoListing/RECALL_APPROVAL_REQUEST_COMMENTS_TEXTAREA",
    RECALL_APPROVAL_REQUEST_RECALL_BUTTON: "PoListing/RECALL_APPROVAL_REQUEST_RECALL_BUTTON",
    RECALLED_SUCCESS_DONE_BUTTON: "PoListing/RECALLED_SUCCESS_DONE_BUTTON",
}