module.exports = {
    createPOButton: "Spo/CREATE_PO_BUTTON",
    //createPOButton:  global.uiElements.get("Spo/CREATE_PO_BUTTON"),
    standardPOButton : "Spo/STANDARD_PO_BUTTON",
    spinner : "Spo/spinner",
 //  spinner : global.uiElements.get("Spo/spinner"),
    poNumberTextbox : "Spo/BasicDetails/PO_NUMBER_TEXTBOX",
    poDescriptionTextbox : "Spo/BasicDetails/PO_DESCRIPTION_TEXTBOX",
    purchaseTypeDropdown : "Spo/BasicDetails/PURCHASE_TYPE_DROPDOWN",
    purchaseTypeValue : "Spo/BasicDetails/PURCHASE_TYPE_VALUE",
    supplierNameTextbox :  "Spo/SupplierDetails/SUPPLIER_NAME_TEXTBOX",
    supplierAddressTextbox : "Spo/SupplierDetails/SUPPLIER_ADDRESS_TEXTBOX",
    paymentTermDropdown : "Spo/SupplierDetails/PAYMENT_TERM_DROPDOWN",
    deliveryTermDropdown : "Spo/SupplierDetails/DELIVERY_TERM_DROPDOWN",
    currencyTextbox :"Spo/SupplierDetails/CURRENCY_TEXTBOX",
    buyerTextbox : "Spo/SupplierDetails/BUYER_TEXTBOX",
    TAB_NAME_LIST: "Spo/TAB_NAME_LIST",
    COST_ALLOCATION_TAB: "Spo/COST_ALLOCATION_TAB",
    ASSIGN_COST_PROJECT_NO_RADIO_BUTTON:"Spo/CostAllocation/ASSIGN_COST_PROJECT_NO_RADIO_BUTTON",
    BOOK_COST_TO_SINGLE_MULTIPLE_COST_CENTER_RADIO_BUTTON: "Spo/CostAllocation/BOOK_COST_TO_SINGLE_MULTIPLE_COST_CENTER_RADIO_BUTTON",
    COST_CENTER_INPUT_FIELD: "Spo/CostAllocation/COST_CENTER_INPUT_FIELD",
    ADD_LINE_ITEM_BUTTON: "SPO/LineItems/ADD_LINE_ITEM_BUTTON",
    ITEM_NAME_INPUT: "Spo/LineItems/ITEM_NAME_INPUT",
    FIRST_ITEMNAME_OPTION: "Spo/LineItems/FIRST_ITEMNAME_OPTION",
    GLACCOUNT: "Spo/LineItems/CostBookingDetails/GLAccount",
    COSTBOOKING_SAVE_BUUTON: "Spo/COSTBOOKING_SAVE_BUUTON",
    REMOVE_ALL_TAXES_BUTTON: "Spo/Taxes/REMOVE_ALL_TAXES_BUTTON",
    SUBMIT_PO_BUTTON: "Spo/SUBMIT_PO_BUTTON",
    CONFIRM_BUTTON: "Spo/CONFIRM_BUTTON",
    VIEW_BASIC_DETAILS_SECTION: "Spo/VIEW_BASIC_DETAILS_SECTION",
};