
module.exports ={
    QUOTED_BY_SUPPLIER_RADIO_BUTTON : "OnlineStore/AddItemDetails/QUOTED_BY_SUPPLIER_RADIO_BUTTON",
    NEED_QUOTE_RADIO_BUTTON : "OnlineStore/AddItemDetails/NEED_QUOTE_RADIO_BUTTON",
    SUPPLIER_TEXTBOX : "OnlineStore/AddItemDetails/SUPPLIER_TEXTBOX",
    QUANTITY_TEXTBOX : "OnlineStore/AddItemDetails/QUANTITY_TEXTBOX",
    UOM_TEXTBOX : "OnlineStore/AddItemDetails/UOM_TEXTBOX",
    PRICE_TEXTBOX : "OnlineStore/AddItemDetails/PRICE_TEXTBOX",
    ADD_TO_CART_BUTTON : "OnlineStore/AddItemDetails/ADD_TO_CART_BUTTON",
    ADD_TO_BASKET_BUTTON : "OnlineStore/AddItemDetails/ADD_TO_BASKET_BUTTON",
    ADD_ITEM_DETAILS_BUTTON : "OnlineStore/ADD_ITEM_DETAILS",
    CURRENCY_TEXTBOX : "OnlineStore/AddItemDetails/CURRENCY_TEXTBOX",
    ZERO_PRICE_ITEM_CHECKBOX : "OnlineStore/AddItemDetails/ZERO_PRICE_ITEM_CHECKBOX",
    ITEM_DESCRIPTION_TEXTBOX : "OnlineStore/AddItemDetails/ITEM_DESCRIPTION_TEXTBOX",
    SUPPLIER_PART_ID_TEXTBOX : "OnlineStore/AddItemDetails/SUPPLIER_PART_ID_TEXTBOX",

}